package Swift.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_NamedEntityDecl_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_NamedEntityDecl_InferenceRule() {
  }
  public void applyRule(final SNode namedEntityDecl, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    if (SPropertyOperations.getBoolean(namedEntityDecl, PROPS.has_explicit_type$5hVM) && SPropertyOperations.getBoolean(namedEntityDecl, PROPS.has_initial_value$5hGL)) {
      ListSequence.fromList(SLinkOperations.getChildren(namedEntityDecl, LINKS.variables$5iCP)).visitAll((var) -> {
        {
          SNode _nodeToCheck_1029348928467 = var;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707679", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707686", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(namedEntityDecl, LINKS.explicit_type$5j6R), "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707681", true), _info_12389875345);
        }
      });
      if (!(typeCheckingContext.isSingleTypeComputation())) {
        {
          SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(namedEntityDecl, LINKS.initial_value$5iRQ);
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, "Incompatible initial value type", "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859059493611", 0, null);
          typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859059493614", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(namedEntityDecl, LINKS.explicit_type$5j6R), "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859059493619", true), true, false, _info_12389875345);
        }
      }
    } else if (SPropertyOperations.getBoolean(namedEntityDecl, PROPS.has_explicit_type$5hVM)) {
      ListSequence.fromList(SLinkOperations.getChildren(namedEntityDecl, LINKS.variables$5iCP)).visitAll((var) -> {
        {
          SNode _nodeToCheck_1029348928467 = var;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707722", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707729", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(namedEntityDecl, LINKS.explicit_type$5j6R), "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707724", true), _info_12389875345);
        }
      });
    } else if (SPropertyOperations.getBoolean(namedEntityDecl, PROPS.has_initial_value$5hGL)) {
      ListSequence.fromList(SLinkOperations.getChildren(namedEntityDecl, LINKS.variables$5iCP)).visitAll((var) -> {
        {
          SNode _nodeToCheck_1029348928467 = var;
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707743", 0, null);
          typeCheckingContext.createLessThanInequality((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707745", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(namedEntityDecl, LINKS.initial_value$5iRQ), "r:0c6516bc-67ad-43d0-9e62-91eb10f7a8b8(Swift.typesystem)", "2928370859057707748", true), false, true, _info_12389875345);
        }
      });
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.NamedEntityDecl$xw;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink variables$5iCP = MetaAdapterFactory.getContainmentLink(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x28a3a9c7f8bd7a87L, 0x28a3a9c7f8bd930fL, "variables");
    /*package*/ static final SContainmentLink explicit_type$5j6R = MetaAdapterFactory.getContainmentLink(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x28a3a9c7f8bd7a87L, 0x28a3a9c7f8bd9311L, "explicit_type");
    /*package*/ static final SContainmentLink initial_value$5iRQ = MetaAdapterFactory.getContainmentLink(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x28a3a9c7f8bd7a87L, 0x28a3a9c7f8bd9310L, "initial_value");
  }

  private static final class PROPS {
    /*package*/ static final SProperty has_explicit_type$5hVM = MetaAdapterFactory.getProperty(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x28a3a9c7f8bd7a87L, 0x28a3a9c7f8bd930cL, "has_explicit_type");
    /*package*/ static final SProperty has_initial_value$5hGL = MetaAdapterFactory.getProperty(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x28a3a9c7f8bd7a87L, 0x28a3a9c7f8bd930bL, "has_initial_value");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept NamedEntityDecl$xw = MetaAdapterFactory.getConcept(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x28a3a9c7f8bd7a87L, "Swift.structure.NamedEntityDecl");
  }
}
