package Swift.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class FloatValue_Constraints extends BaseConstraintsDescriptor {
  public FloatValue_Constraints() {
    super(CONCEPTS.FloatValue$16);
  }

  public static class BeforeDecimal_Property extends BasePropertyConstraintsDescriptor {
    public BeforeDecimal_Property(ConstraintsDescriptor container) {
      super(PROPS.beforeDecimal$hopI, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:cadaf8f5-bf2c-4eea-8e82-c1c814da96ef(Swift.constraints)", "175470559282134595"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      return propertyValue.matches("-?([0-9_]+|0x[0-9A-F_]+)");
    }
  }
  public static class AfterDecimal_Property extends BasePropertyConstraintsDescriptor {
    public AfterDecimal_Property(ConstraintsDescriptor container) {
      super(PROPS.afterDecimal$hoRK, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castString(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:cadaf8f5-bf2c-4eea-8e82-c1c814da96ef(Swift.constraints)", "175470559282120009"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, String propertyValue) {
      if (SPropertyOperations.getString(node, PROPS.beforeDecimal$hopI).matches("0x[0-9A-F_]+")) {
        return propertyValue.matches("-?([0-9_]+|0x[0-9A-F_]+)[pP]-?[0-9_]+");
      } else {
        return propertyValue.matches("-?([0-9_]+|0x[0-9A-F_]+)([eE]-?[0-9_]+)?");
      }
    }
  }
  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(PROPS.beforeDecimal$hopI, new BeforeDecimal_Property(this));
    properties.put(PROPS.afterDecimal$hoRK, new AfterDecimal_Property(this));
    return properties;
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept FloatValue$16 = MetaAdapterFactory.getConcept(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x26f658b4275d3c4L, "Swift.structure.FloatValue");
  }

  private static final class PROPS {
    /*package*/ static final SProperty beforeDecimal$hopI = MetaAdapterFactory.getProperty(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x26f658b4275d3c4L, 0x26f658b428c881eL, "beforeDecimal");
    /*package*/ static final SProperty afterDecimal$hoRK = MetaAdapterFactory.getProperty(0xfe2099137e444724L, 0xa9e768530fec997cL, 0x26f658b4275d3c4L, 0x26f658b428c8820L, "afterDecimal");
  }
}
